import Head from "next/head";
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Image from "next/image";
import Link from 'next/link';

import{AiFillTwitterCircle, AiFillLinkedin, AiFillGithub, AiFillCode} from "react-icons/ai";
import { SiLeetcode } from 'react-icons/fa';
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";

import deved from "../../public/dev-ed-wave.png";

import Java from "../../public/java.png";
import MERN from "../../public/MERN-logo.png";
import CourseWork from "../../public/courseWork.png";
import BlockChain from "../../public/blockchain.png";

import BreakingBad from "../../public/breakingBad.png";
import BookStore from "../../public/bookstore2.png";
import Ecommerse from "../../public/Ecommerce.png";
import FileSharingDapp from "../../public/fileSharingDapp.png";
import github from "../../public/github.png";
import inshort from "../../public/inshort.png";
import recipeApp from "../../public/recipeApp.png";
import resume from "../../public/Nishant_BTech_Nov2023.pdf";


import Footer from "./footer";
import Timeline from "./timeline";
import Test from "./test";


function Home(){

  const [darkMode, setDarkMode] = useState(true);

  return (
    <div className={darkMode ? "dark" : ""}>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="py-10 mb-12 flex justify-between dark:text-white">
            <h1 className="font-burtons pr-2 text-gray-800 text-xl  dark:text-yellow-200 ">developedBy_Nishant</h1>
            <ul className="flex items-center">
              <li className=" text-gray-800 text-xl  dark:text-white ">
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl "
                />
              </li>
<li>
  <a
    className="bg-gradient-to-r from-cyan-500 text-to-teal-500 text-white px-4 py-2 border-none rounded-md ml-8"
    href={resume}  // Replace with the actual path to your resume file
    download="Nishant_BTech_Nov2023.pdf"
  >
    Resume
  </a>
</li>

            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl font-burtons py-2 text-teal-600 font-medium dark:text-teal-400 md:text-6xl">
              Nishant Patil
            </h2>
            <h3 className="text-2xl font-burtons py-2 text-gray-900 dark:text-white md:text-3xl">
              IT'24 undergrad
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
               "I'm not always sarcastic, sometimes I'm sleeping." <br/>
               Exploring Web3 /  MERN / JAVA  / Data Structure & Algorithms <br/>
               <span className="text-teal-500  dark:text-yellow-100 "> let's get cracking! </span>
               
            </p>

            {/* --------------------- Handle icons here------------------------ */}
            <div className="text-5xl flex justify-center gap-16 py-3 text-gray-600 dark:text-gray-400">

                        <a
                            href="https://leetcode.com/Nishant_219/"
                            className={"transition-colors hover:text-yellow-400"}
                            target="_blank"
                            rel="noreferrer"
                        >
                            <AiFillCode/>
                        </a>


                        <a
                            href="https://www.linkedin.com/in/nishantpatil219"
                            className={"transition-colors hover:text-green-600"}
                            target="_blank"
                            rel="noreferrer"
                        >
                            <AiFillLinkedin /> 
                        </a>


                        <a
                            href="https://github.com/nishant219"
                            className={"transition-colors hover:text-teal-500"}
                            target="_blank"
                            rel="noreferrer"
                        >
                            <AiFillGithub />
                        </a>
                        
            </div>

            <section > 
            <Test/>
            </section>

            <div className="mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 relative overflow-hidden mt-20 md:h-96 md:w-96">
              <Image src={deved} layout="fill" objectFit="cover" />
            </div>
          </div>

        </section>




{/* _______________________________ TimeLine section ______________________________________________ */}


        <section className="border mt-7 mb-2 border-solid rounded-lg hover:shadow-lg focus:shadow-2xl border-teal-300 p-4">
            <Timeline/>
        </section>


{/* _______________________________ Technical competencies section ______________________________________________ */}


        <section className="p-7">

          <div>
            <h3 className="text-3xl mt-5 font-bold text-black py-1 dark:text-white "> Technical competencies </h3>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
              
              I am currently delving into the world of <span className="text-teal-500"> Blockchain and web3</span>, utilizing techstacks such as Solidity and libraries like ether.js. 
              Additionally, I am exploring the <span className="text-teal-500"> MERN Stack </span> for full-stack web development. 
              I have a strong interest in <span className="text-teal-500"> Data Structures and Algorithms </span> and am continuously working on improving my skills in these areas through DS-Algo practice and a bit of competitive programming.
              Apart from screen time, I also enjoy spending time with pen and paper.
              
            </p>

            <p className="text-md py-2 leading-8 text-gray-950 dark:text-gray-100">
            I approach my work with quiet confidence, a natural curiosity, and a continuous drive to enhance my design abilities one problem at a time.
            </p>

          </div>

          {/* ____ card goes here _____ */}

          <div className="lg:flex gap-10">

            <div className="text-center shadow-xl p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={Java} width={100} height={100} />
              <h3 className="text-lg text-gray-600 font-medium pt-8 pb-2  ">
                JAVA
              </h3>
              <h4 className="py-4 text-teal-600">Familiar with: </h4>
              <p className="text-gray-800 py-1">OOP concepts,</p>
              <p className="text-gray-800 py-1">Java Collections</p>
            </div>


            <div className="text-center shadow-xl p-10 rounded-xl my-10  dark:bg-white flex-1">
              <Image src={BlockChain} width={100} height={100} />
              <h3 className="text-lg text-gray-600 font-medium pt-8 pb-2  ">
                BLOCK_CHAIN
              </h3>
              <h4 className="py-4 text-teal-600"> Conversant with: </h4>
              <p className="text-gray-800 py-1">Solidity</p>
              <p className="text-gray-800 py-1">Ether.JS</p>
              <p className="text-gray-800 py-1">HardHat</p>
            </div>


            <div className="text-center shadow-xl p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={MERN} width={100} height={100} />
              <h3 className="text-lg text-gray-600 font-medium pt-8 pb-2 ">
                MERN
              </h3>
              <h4 className="py-4 text-teal-600">Conversant with:</h4>
              <p className="text-gray-800 py-1">JS /React/Next </p>
              <p className="text-gray-800 py-1">Express/NodeJs</p>
              <p className="text-gray-800 py-1"> MongoDB </p>
              <p className="text-gray-800 py-1">Git/Postman/GitHub</p>
            </div>

            <div className="text-center shadow-xl p-10 rounded-xl my-10 dark:bg-white flex-1">
              <Image src={CourseWork} width={100} height={100} />
              <h3 className="text-lg text-gray-600 font-medium pt-8 pb-2 ">COURSE_WORK</h3>
              <h4 className="py-4 text-teal-600"> Informed about: </h4>
              <p className="text-gray-800 py-1">OOP</p>
              <p className="text-gray-800 py-1">DBMS</p>
              <p className="text-gray-800 py-1">OS</p>
              <p className="text-gray-800 py-1">CN</p>
            </div>

          </div>
        </section>


{/* _______________________________ Portofolio section ______________________________________________ */}

        <section className="py-10 mt-7">
          <div>

            <h3 className="text-3xl font-bold text-black py-1 dark:text-white ">Portofolio</h3>

            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">

              Ever since I began my journey as an undergraduate in IT, I have been <span className="text-teal-500"> fascinated </span> by web development.
              I took a course on the subject and delved deeper into it. 
              <br/> At that time, Blockchain was the new <span className="text-teal-500"> buzz </span> in the market, so I decided to try my hand at it by completing some projects in the web3 domain.
              It is a highly <span className="text-teal-500"> promising technology </span> that has caught my attention. 
              I also find data structures and algorithms equally worth exploring.
              
            </p>
            <p className="text-md py-2 leading-8 text-gray-800 dark:text-gray-200">
            I have listed some of my <span className="text-teal-500"> projects </span> below for you to review:
            </p>
          </div>

          {/* cards - project images */}

          <div className="flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap">

            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={BreakingBad}
              />
              <p className="text-gray-950  dark:text-white">Breaking Bad Character Searcher :
                <a href="https://breaking-bad-api-nishant.netlify.app/"> <span className="text-yellow-200"> Link </span> </a>
              </p>
            </div>


            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={Ecommerse}
              />
              <p className="text-gray-950  dark:text-white"> Ecommerce website (MERN) :
                <a href="https://github.com/nishant219/LCO-ECommerseWeb"> <span className="text-yellow-200"> Link </span> </a>
              </p>
            </div>


            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={recipeApp}
              />
              <p className="text-gray-950  dark:text-white"> Recipe CRUD website (MERN) :
                <a href="https://mern-delight.netlify.app/"> <span className="text-yellow-200"> Link </span> </a>
              </p>
            </div>


            <div className="basis-1/3 flex-1 mt-20 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={FileSharingDapp}
              />
              <p className="text-gray-950  dark:text-white"> File Sharing Dapp :
                <a href="https://file-sharing-mern-client.vercel.app/"> <span className="text-yellow-200"> Link </span> </a>
              </p>
            </div>


            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={BookStore}
              />
              <p className="text-gray-950 dark:text-white"> MERN-BookStore :
                <a href="https://mern-book-store-client.vercel.app/"> <span className="text-yellow-200"> Link </span> </a>
              </p>
            </div>


            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover"
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={github}
              />
              <p className="text-gray-950  dark:text-white"> `FireHub` github_API+firebase profile searcher :
                <a href="https://firehub-219.netlify.app/"> <span className="text-yellow-200"> Link </span> </a>
              </p>
            </div>


            <div className="basis-1/3 flex-1 ">
              <Image
                className="rounded-lg object-cover "
                width={"100%"}
                height={"100%"}
                layout="responsive"
                src={inshort}
              />
              <p className="text-gray-950  dark:text-white"> Inshort news app web clone :
                <a href="https://inshort-clone-client.vercel.app/"> <span className="text-yellow-200"> Link </span> </a>
              </p>
            </div>


          </div>
        </section>


{/* _______________________________footer section______________________________________________ */}

        <section>
          <Footer/>
        </section>

        
      </main>
    </div>
  );
}


export default Home;
